import type { Metadata } from "next";
import "./globals.css";
import { Tomorrow } from "next/font/google";
import { Analytics } from '@vercel/analytics/react';

const tomorrow = Tomorrow({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Pokemon Card Collector",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={tomorrow.className}>
        {children}
        <Analytics />
      </body>
    </html >
  );
}
